name: paging_plus
version: 1.0.0

description: Lightweight pagination package. Calculate pages, determine next page to fetch, and handle load-more with optimized data fetching for Flutter & Dart.

repository: https://github.com/hossameldinmi/paging_plus

topics:
  - page
  - paging
  - pagination
  - infinite-scroll
  - load-more

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  equatable: ^2.0.7


dev_dependencies:
  test: ^1.26.3
